server:
  port: 8081

spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret:
      key: ${JWT_KEY}

coolsms:
  access: ${COOLSMS_ACCESS}
  secret: ${COOLSMS_SECRET}
  phone: ${COOLSMS_PHONE}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS}
      secretKey: ${S3_SECRET}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
    com.project.findme.infrastructure.feign: debug

feign:
  client:
    config:
      default:
        logger-level: full

socket:
  port: 8082

messages:
  basename: i18n/exception
  encoding: UTF-8